# golangci-lint configuration for Cartographus
# https://golangci-lint.run/docs/configuration/
# v2 configuration format (requires golangci-lint v2.x)

version: "2"

run:
  timeout: 5m
  build-tags:
    - wal
    - nats

linters:
  # v2 replacement for 'disable-all: true'
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      # Exclude specific functions where error checking is not meaningful
      exclude-functions:
        - (io.Writer).Write
        - (net/http.ResponseWriter).Write
        # Common Close patterns - defer Close() errors are typically ignored
        - (io.Closer).Close
        - (*os.File).Close
        - (io.ReadCloser).Close
        - (*net/http.Response).Body.Close
        # SQL rows Close
        - (*database/sql.Rows).Close
        # OS operations in cleanup/setup code
        - os.Remove
        - os.RemoveAll
        - os.Setenv
        - os.Unsetenv
    staticcheck:
      # Disable style suggestions (QF = quickfix suggestions)
      checks:
        - "all"
        - "-QF*"

  exclusions:
    # v2 replacement for 'issues.exclude-dirs'
    paths:
      - vendor
      - docs
    rules:
      # Exclude errcheck for test files
      - linters:
          - errcheck
        path: _test\.go$
      # Ignore SA9003 empty branch in test/fuzz files (often intentional)
      - linters:
          - staticcheck
        path: (_test|_fuzz)\.go$
        text: SA9003
      # Ignore QF* style suggestions
      - linters:
          - staticcheck
        text: "^QF"
      # Ignore unchecked Close() in defer statements (common Go pattern)
      - linters:
          - errcheck
        text: "Close"
      # Ignore unchecked Body.Close (common HTTP pattern)
      - linters:
          - errcheck
        text: "Body\\.Close"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 100
  # Maximum count of issues with the same text
  max-same-issues: 20
