# golangci-lint configuration for Cartographus
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  build-tags:
    - wal
    - nats

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Exclude specific functions where error checking is not meaningful
    exclude-functions:
      - (io.Writer).Write
      - (net/http.ResponseWriter).Write

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10

  # Exclude directories
  exclude-dirs:
    - vendor
    - docs
