# golangci-lint configuration for Cartographus
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  build-tags:
    - wal
    - nats
  skip-dirs:
    - vendor
    - docs

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - deadcode      # deprecated
    - structcheck   # deprecated
    - varcheck      # deprecated

linters-settings:
  errcheck:
    # Exclude specific functions where error checking is not meaningful
    exclude-functions:
      - (io.Writer).Write
      - (net/http.ResponseWriter).Write

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10

  # Don't hide issues in vendor, generated files, etc.
  exclude-use-default: false

  # New issues introduced in the last N commits
  new: false
