name: Feature Request
description: Suggest a new feature or enhancement for Cartographus
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with Cartographus's purpose as a media server analytics platform
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: A clear description of the problem, e.g., "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the application does this affect?
      options:
        - Map Visualization
        - Charts/Analytics
        - Dashboard
        - API
        - Media Server Integration
        - Authentication/Authorization
        - Performance
        - Data Import/Export
        - Detection/Security Rules
        - User Interface
        - Mobile/Responsive
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your use case?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help test the implementation
        - label: I can provide detailed design/mockups

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: |
        If applicable, add mockups, diagrams, or links to similar implementations
      placeholder: Add images, links, or descriptions...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Any additional information...
