// Cartographus - Media Server Analytics and Geographic Visualization
// Copyright 2026 Tom F. (tomtom215)
// SPDX-License-Identifier: AGPL-3.0-or-later
// https://github.com/tomtom215/cartographus

//go:build ignore

// This is a ONE-TIME generator for the static test dataset.
// Run with: go run generate_static_data.go > static_seed_data.sql
//
// IMPORTANT: This file uses ZERO randomness. All values are derived
// deterministically from the record ID. The output is 100% reproducible.

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"
)

const (
	totalRecords = 550
	numUsers     = 10
	numMovies    = 220 // 40%
	numEpisodes  = 275 // 50%
	numTracks    = 55  // 10%
)

// User profiles - completely fixed
var users = []struct {
	ID           int
	Username     string
	FriendlyName string
	IPAddress    string
	City         string
	Region       string
	Country      string
	PostalCode   string
	Latitude     float64
	Longitude    float64
	Platform     string
	Player       string
	Product      string
	Location     string // lan or wan
	Bandwidth    int
}{
	{1, "admin", "Admin User", "192.168.1.100", "New York", "NY", "US", "10001", 40.7128, -74.0060, "Chrome", "Plex Web", "Plex Web", "lan", 50000},
	{2, "moviebuff", "Movie Buff", "73.45.123.89", "Los Angeles", "CA", "US", "90001", 34.0522, -118.2437, "Roku", "Plex for Roku", "Plex for Roku", "wan", 25000},
	{3, "tvaddict", "TV Addict", "98.234.56.78", "Chicago", "IL", "US", "60601", 41.8781, -87.6298, "Android", "Plex for Android (TV)", "Plex for Android (TV)", "wan", 20000},
	{4, "musiclover", "Music Lover", "82.132.45.67", "London", "ENG", "GB", "EC1A", 51.5074, -0.1278, "iOS", "Plex for iOS", "Plex for iOS", "wan", 15000},
	{5, "familyaccount", "Family Account", "176.89.234.12", "Berlin", "BE", "DE", "10115", 52.5200, 13.4050, "Samsung", "Plex for Samsung", "Plex for Samsung", "wan", 30000},
	{6, "nightowl", "Night Owl", "45.67.89.123", "Tokyo", "TK", "JP", "100-0001", 35.6762, 139.6503, "Apple TV", "Plex for Apple TV", "Plex for Apple TV", "wan", 35000},
	{7, "casualviewer", "Casual Viewer", "203.45.67.89", "Sydney", "NSW", "AU", "2000", -33.8688, 151.2093, "Firefox", "Plex Web", "Plex Web", "wan", 22000},
	{8, "mobilewatcher", "Mobile Watcher", "156.78.90.234", "Toronto", "ON", "CA", "M5V", 43.6532, -79.3832, "Android", "Plex for Android (Mobile)", "Plex for Android", "wan", 12000},
	{9, "weekendwarrior", "Weekend Warrior", "89.123.45.67", "Paris", "IDF", "FR", "75001", 48.8566, 2.3522, "PlayStation", "Plex for PlayStation", "Plex for PlayStation", "wan", 28000},
	{10, "bingewatcher", "Binge Watcher", "112.45.78.90", "Singapore", "SG", "SG", "018956", 1.3521, 103.8198, "Xbox", "Plex for Xbox", "Plex for Xbox", "wan", 32000},
}

// Fixed movie titles
var movieTitles = []string{
	"The Matrix", "Inception", "Interstellar", "The Dark Knight", "Pulp Fiction",
	"Fight Club", "Forrest Gump", "The Shawshank Redemption", "Goodfellas", "The Godfather",
	"Jurassic Park", "Titanic", "Avatar", "The Avengers", "Iron Man",
	"Spider-Man", "Batman Begins", "Wonder Woman", "Black Panther", "Guardians of Galaxy",
	"Star Wars", "Lord of the Rings", "Harry Potter", "Back to the Future", "E.T.",
}

// Fixed TV shows
var tvShows = []string{
	"Breaking Bad", "Game of Thrones", "The Office", "Friends", "Stranger Things",
	"The Mandalorian", "The Crown", "Succession", "Ted Lasso", "House of Dragon",
}

// Fixed artists
var artists = []string{
	"The Beatles", "Pink Floyd", "Led Zeppelin", "Queen", "David Bowie",
}

func generateMachineID(username string) string {
	hash := sha256.Sum256([]byte(username + "-machine-id"))
	return hex.EncodeToString(hash[:16])
}

func main() {
	// Base timestamp: July 1, 2025 00:00:00 UTC
	// End timestamp: December 1, 2025 00:00:00 UTC (5 months later)
	// IMPORTANT: Sync lookback is 180 days (4320h). From Dec 23, 2025, this goes back to June 26.
	// Starting on July 1 ensures ALL records are within the lookback window (5 day buffer).
	baseTime := time.Date(2025, 7, 1, 0, 0, 0, 0, time.UTC)
	endTime := time.Date(2025, 12, 1, 0, 0, 0, 0, time.UTC)

	// Calculate interval to spread records evenly across 5 months
	totalDuration := endTime.Sub(baseTime)                             // ~153 days
	intervalPerRecord := totalDuration / time.Duration(totalRecords+1) // ~6.7 hours per record

	fmt.Println(`-- =============================================================================
-- STATIC CURATED TEST DATASET FOR TAUTULLI SYNC TESTING
-- =============================================================================
-- Generated by: go run generate_static_data.go
--
-- CRITICAL PROPERTIES:
-- - ZERO randomness: Every value is derived from record ID
-- - 100% deterministic: Identical output every time
-- - 100% auditable: Every record traceable by ID
--
-- Dataset Summary:
-- - Total records: 550
-- - Movies: 220 (IDs 1-220)
-- - Episodes: 275 (IDs 221-495)
-- - Tracks: 55 (IDs 496-550)
-- - Users: 10 (55 records each)
-- - Date range: July 1, 2025 - December 1, 2025 (within 180-day lookback)
--
-- Session Key Format: 'static-session-XXXX' where XXXX is zero-padded ID
-- This ensures unique, traceable session keys for every record.
-- =============================================================================

-- Users table
`)

	// Generate users
	for _, u := range users {
		fmt.Printf(`INSERT INTO users (id, user_id, username, friendly_name, thumb, email, is_active, is_admin, do_notify, keep_history) VALUES (%d, %d, '%s', '%s', '/library/users/%d/thumb', '%s@test.local', 1, %d, 1, 1);
`, u.ID, u.ID, u.Username, u.FriendlyName, u.ID, u.Username, boolToInt(u.ID == 1))
	}

	fmt.Println("\n-- Session history records")

	// Generate all 550 records
	for id := 1; id <= totalRecords; id++ {
		userIdx := (id - 1) % numUsers
		user := users[userIdx]
		machineID := generateMachineID(user.Username)

		// Deterministic timestamp: spread evenly across 6 months (June 1 - Dec 1, 2025)
		sessionTime := baseTime.Add(time.Duration(id) * intervalPerRecord)
		started := sessionTime.Unix()

		// Duration based on media type
		var mediaType string
		var duration int
		var ratingKey int
		var title string
		var parentRatingKey, grandparentRatingKey string
		var parentTitle, grandparentTitle string
		var fullTitle string
		var sectionID int
		var libraryName string

		if id <= numMovies {
			// Movies (IDs 1-220)
			mediaType = "movie"
			duration = 7200 // 2 hours
			ratingKey = 1000 + id
			title = movieTitles[(id-1)%len(movieTitles)]
			fullTitle = title
			sectionID = 1
			libraryName = "Movies"
			parentRatingKey = "NULL"
			grandparentRatingKey = "NULL"
			parentTitle = "NULL"
			grandparentTitle = "NULL"
		} else if id <= numMovies+numEpisodes {
			// Episodes (IDs 221-495)
			mediaType = "episode"
			duration = 3600 // 1 hour
			episodeIdx := id - numMovies - 1
			showIdx := episodeIdx % len(tvShows)
			seasonNum := (episodeIdx/10)%5 + 1
			episodeNum := episodeIdx%10 + 1
			ratingKey = 4000 + id
			title = fmt.Sprintf("Episode %d", episodeNum)
			parentTitle = fmt.Sprintf("'Season %d'", seasonNum)
			grandparentTitle = fmt.Sprintf("'%s'", tvShows[showIdx])
			fullTitle = fmt.Sprintf("%s - S%02dE%02d - %s", tvShows[showIdx], seasonNum, episodeNum, title)
			parentRatingKey = fmt.Sprintf("%d", 3000+showIdx*10+seasonNum)
			grandparentRatingKey = fmt.Sprintf("%d", 2000+showIdx)
			sectionID = 2
			libraryName = "TV Shows"
		} else {
			// Tracks (IDs 496-550)
			mediaType = "track"
			duration = 300 // 5 minutes
			trackIdx := id - numMovies - numEpisodes - 1
			artistIdx := trackIdx % len(artists)
			albumNum := (trackIdx/5)%3 + 1
			trackNum := trackIdx%5 + 1
			ratingKey = 7000 + id
			title = fmt.Sprintf("Track %d", trackNum)
			parentTitle = fmt.Sprintf("'Album %d'", albumNum)
			grandparentTitle = fmt.Sprintf("'%s'", artists[artistIdx])
			fullTitle = fmt.Sprintf("%s - %s", artists[artistIdx], title)
			parentRatingKey = fmt.Sprintf("%d", 6000+artistIdx*10+albumNum)
			grandparentRatingKey = fmt.Sprintf("%d", 5000+artistIdx)
			sectionID = 3
			libraryName = "Music"
		}

		stopped := started + int64(duration)
		sessionKey := fmt.Sprintf("static-session-%04d", id)
		viewOffset := duration * 1000 // milliseconds
		transcodeDecision := "direct play"
		if user.Location == "wan" && id%3 == 0 {
			transcodeDecision = "transcode"
		}

		// Session history
		fmt.Printf(`INSERT INTO session_history (id, reference_id, date, started, stopped, rating_key, parent_rating_key, grandparent_rating_key, media_type, user_id, user, friendly_name, ip_address, platform, player, product, machine_id, bandwidth, location, session_key, view_offset, percent_complete, paused_counter, transcode_decision, geo_city, geo_region, geo_country, geo_code, geo_latitude, geo_longitude) VALUES (%d, %d, %d, %d, %d, %d, %s, %s, '%s', %d, '%s', '%s', '%s', '%s', '%s', '%s', '%s', %d, '%s', '%s', %d, 100, 0, '%s', '%s', '%s', '%s', '%s', %.4f, %.4f);
`,
			id, id, started, started, stopped, ratingKey, parentRatingKey, grandparentRatingKey,
			mediaType, user.ID, user.Username, user.FriendlyName, user.IPAddress,
			user.Platform, user.Player, user.Product, machineID,
			user.Bandwidth, user.Location, sessionKey, viewOffset,
			transcodeDecision, user.City, user.Region, user.Country, user.PostalCode,
			user.Latitude, user.Longitude)

		// Session history metadata
		year := 2020 + (id % 5)
		durationMs := duration * 1000
		guid := fmt.Sprintf("plex://%s/%s", mediaType, generateGUID(ratingKey))

		if parentTitle == "NULL" {
			fmt.Printf(`INSERT INTO session_history_metadata (id, rating_key, parent_rating_key, grandparent_rating_key, title, parent_title, grandparent_title, full_title, section_id, library_name, media_type, year, duration, guid) VALUES (%d, %d, NULL, NULL, '%s', NULL, NULL, '%s', %d, '%s', '%s', %d, %d, '%s');
`, id, ratingKey, title, fullTitle, sectionID, libraryName, mediaType, year, durationMs, guid)
		} else {
			fmt.Printf(`INSERT INTO session_history_metadata (id, rating_key, parent_rating_key, grandparent_rating_key, title, parent_title, grandparent_title, full_title, section_id, library_name, media_type, year, duration, guid) VALUES (%d, %d, %s, %s, '%s', %s, %s, '%s', %d, '%s', '%s', %d, %d, '%s');
`, id, ratingKey, parentRatingKey, grandparentRatingKey, title, parentTitle, grandparentTitle, fullTitle, sectionID, libraryName, mediaType, year, durationMs, guid)
		}

		// Session history media info
		videoCodec := "h264"
		audioCodec := "aac"
		if mediaType == "track" {
			videoCodec = ""
			audioCodec = "flac"
		}
		fmt.Printf(`INSERT INTO session_history_media_info (id, video_codec, audio_codec, container, transcode_decision) VALUES (%d, '%s', '%s', 'mkv', '%s');
`, id, videoCodec, audioCodec, transcodeDecision)
	}

	fmt.Println(`
-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- Run these to verify the dataset:
-- SELECT COUNT(*) FROM session_history;                    -- Expected: 550
-- SELECT COUNT(*) FROM session_history WHERE media_type='movie';    -- Expected: 220
-- SELECT COUNT(*) FROM session_history WHERE media_type='episode';  -- Expected: 275
-- SELECT COUNT(*) FROM session_history WHERE media_type='track';    -- Expected: 55
-- SELECT COUNT(DISTINCT user_id) FROM session_history;     -- Expected: 10
-- SELECT user_id, COUNT(*) FROM session_history GROUP BY user_id;   -- Expected: 55 each
-- =============================================================================`)
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func generateGUID(key int) string {
	hash := sha256.Sum256([]byte(fmt.Sprintf("%d", key)))
	return hex.EncodeToString(hash[:12])
}
