// Cartographus - Media Server Analytics and Geographic Visualization
// Copyright 2026 Tom F. (tomtom215)
// SPDX-License-Identifier: AGPL-3.0-or-later
// https://github.com/tomtom215/cartographus

/*
Package docs provides Swagger/OpenAPI documentation for the Cartographus API.

This package contains auto-generated Swagger specification files used to serve
API documentation at the /swagger endpoint. The specification is generated
from annotations in the source code using swaggo/swag.

# Generated Files

The following files are auto-generated and should not be edited directly:

  - docs.go: Go code containing the Swagger spec (generated by swag init)
  - swagger.json: Swagger 2.0 specification in JSON format
  - swagger.yaml: Swagger 2.0 specification in YAML format

# Regenerating Documentation

To update the API documentation after modifying endpoint annotations:

	# Install swag CLI if not already installed
	go install github.com/swaggo/swag/cmd/swag@latest

	# Regenerate Swagger files from annotations
	swag init -g cmd/server/docs.go -o docs/

	# Verify the generated files
	go build ./docs/...

# Annotation Format

Swagger annotations are placed in Go comments before handlers:

	// GetUsers godoc
	// @Summary      List users
	// @Description  Get paginated list of users
	// @Tags         users
	// @Accept       json
	// @Produce      json
	// @Param        limit   query  int  false  "Max results"  default(100)
	// @Param        offset  query  int  false  "Offset"       default(0)
	// @Success      200  {object}  models.APIResponse{data=[]models.User}
	// @Failure      401  {object}  models.APIError
	// @Router       /users [get]
	// @Security     BearerAuth
	func (h *Handler) GetUsers(w http.ResponseWriter, r *http.Request) {
	    // ...
	}

# API Categories

The API is organized into the following tag groups:

Core:
  - Health checks and server information
  - System statistics and diagnostics

Analytics:
  - Playback analytics (45+ endpoints)
  - Temporal, spatial, and user-based queries
  - Aggregations and trends

Spatial:
  - Geographic clustering
  - H3 hexagonal aggregation
  - Bounding box queries

Tautulli Proxy:
  - Pass-through to Tautulli API (60+ endpoints)
  - Activity, history, metadata queries

WebSocket:
  - Real-time playback notifications
  - Live statistics updates

Export:
  - CSV export with filtering
  - GeoJSON export for mapping
  - GeoParquet for analytics tools

Admin:
  - Sync management (start/stop/status)
  - Backup operations
  - Configuration endpoints

# Swagger UI

When the server is running, interactive API documentation is available at:

	http://localhost:3857/swagger/index.html

The Swagger UI provides:
  - Interactive endpoint testing
  - Request/response examples
  - Schema documentation
  - Authentication configuration

# Authentication

Most endpoints require JWT authentication via HTTP-only cookie:

 1. POST /api/v1/auth/login with credentials
 2. Server sets token cookie
 3. Subsequent requests include cookie automatically

For Swagger UI testing, authenticate first via the login endpoint,
then the cookie will be included in subsequent requests.

# Rate Limiting

Rate limit headers are included in all responses:

	X-RateLimit-Limit: 100      # Max requests per window
	X-RateLimit-Remaining: 95   # Remaining requests
	X-RateLimit-Reset: 1609459200  # Window reset timestamp

Default limits:
  - Authentication endpoints: 5 requests/minute
  - Analytics endpoints: 1000 requests/minute
  - Default: 100 requests/minute

# See Also

  - internal/api: Handler implementations with annotations
  - cmd/server/docs.go: Main Swagger entry point annotations
  - https://github.com/swaggo/swag: Swag documentation generator
  - https://swagger.io/specification/v2/: Swagger 2.0 specification
*/
package docs
